version: "3.8"
services:
  db:
    image: postgres:16
    container_name: db_banner
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: pheezz
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avito_banner
    ports:
      - 5460:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pheezz -d avito_banner"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis_banner

  banner_app:
    build:
      context: .
    container_name: banner_app
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8871:8000
    depends_on:
      - db
      - redis

volumes:
  postgresdata: